name: Markus Kainu home
description: Something here
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
higlighter: rouge
baseurl: http://muuankarski.github.io
analytics :
  provider : google
  google :
    tracking_id : 'UA-46324386-1'
  getclicky :
  site_id :
